---
- name: DBServers-Setup
  hosts: dbservers
  become: yes
  tasks:
    - name: Install mariadb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: present

    - name: Install pymysql
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present

    - name: Start the mariaDB-server
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new Database with name 'accounts'
      community.mysql.mysql_db:
        name: accounts
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Create a database user with name 'vprofile'
      community.mysql.mysql_user:
        name: vprofile
        password: "blueshark@123"
        priv: "*.*:ALL"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
        #https://docs.ansible.com/ansible/2.9/modules/list_of_database_modules.html
